# Backstage catalog-info.yaml
# See https://backstage.io/docs/features/software-catalog/descriptor-format
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  # Note: {{ .ProjectKebab }} will be replaced by scaffold with the project name
  name: shell-generated-blueprint
  # title: Generated Kitchen-Sink Application Template
  description: Bazel project using Aspect Workflows
  annotations:
    # this could also be `url:<url>` if the documentation isn't in the same location
    backstage.io/techdocs-ref: dir:.
    # backstage.io/source-template: template:default/springboot-template
  tags:
    - bazel
    - aspect-workflows
    - shell
  links:
    - url: https://github.com/BlueCentre/shell
      title: Repository
      icon: github
spec:
  type: template
  system: software-foundation
  lifecycle: experimental
  # TODO: Update owner to match your team/organization
  owner: team-platform
  # dependsOn:
  #   - compontent:default/aspect-workflows-template
  subcomponentOf: application-blueprint-generator
